### ISSUE TITLE
Question: Full Sized Pi?

### ISSUE THREAD

**Issue by poblabs** [earlmckay/susi-radio#1]
Hi, will the 3d printed box be able to fit a full sized Raspberry Pi 4?

**Comment by poblabs** [comment]
Actually, I do have a Pi Zero, so I'll give this a try as is. Thanks!

**Comment by earlmckay** [comment]
> Hi, will the 3d printed box be able to fit a full sized Raspberry Pi 4?

Hi, yes, a Raspberry 4 fits in there too, but there are no matching screw holes for it.
